[book]
title = "procon/"
description = "procon collections in Rust"
authors = ["@cympfh"]
language = "ja"
theme = "light"

[build]
src_dir = "src"
output_dir = "./"
base_path = "/procon"

[toc]
show_sections = "current"  # "current"

[[pages]]
title = "代数"

[[pages]]
title = "モノイド"
level = 2
items = [
  { title = "モノイドの定義", path = "algebra.monoid.md" },
  { title = "Min/Max モノイド", path = "algebra.monoid.minmax.md" },
  { title = "Sum モノイド", path = "algebra.monoid.sum.md" },
]

[[pages]]
title = "(乗法)群と加法群"
path = "algebra.group.md"

[[pages]]
title = "環"
path = "algebra.ring.md"

[[pages]]
title = "体"
path = "algebra.field.md"

[[pages]]
title = "加群"
path = "algebra.module.md"

[[pages]]
title = "有理数"
path = "algebra.ratio.md"

[[pages]]
title = "虚数"
path = "algebra.complex.md"

[[pages]]
title = "行列"
path = "algebra.matrix.md"

[[pages]]
title = "超数"
path = "algebra.hyper.md"

[[pages]]
title = "Float"
path = "algebra.float.md"

[[pages]]
title = "ModInt"
path = "algebra.modint.md"

[[pages]]
title = "作用"
items = [
  { title = "(モノイド)作用の定義", path = "algebra.act.md" },
  { title = "加算作用", path = "algebra.act.add.md" },
  { title = "代入作用", path = "algebra.act.assign.md" },
]
