[book]
title = "procon/"
description = "procon collections in Rust"
authors = ["@cympfh"]
language = "ja"
theme = "light"

[build]
src_dir = "src"
output_dir = "./"
# base_path = "/procon"
base_path = "./" # DEBUG

[toc]
show_sections = "current"  # "current"
foldlevel = 1

[[pages]]
title = "代数"

[[pages]]
title = "モノイド"
level = 2
items = [
  { title = "モノイドの定義", path = "algebra.monoid.md" },
  { title = "Min/Max モノイド", path = "algebra.monoid.minmax.md" },
  { title = "Sum モノイド", path = "algebra.monoid.sum.md" },
]

[[pages]]
title = "群・環・体"
level = 2
items = [
  { title = "(乗法)群と加法群", path = "algebra.group.md" },
  { title = "環", path = "algebra.ring.md" },
  { title = "体", path = "algebra.field.md" },
  { title = "加群", path = "algebra.module.md" },
]

[[pages]]
title = "数・行列"
level = 2
items = [
  { title = "有理数", path = "algebra.ratio.md" },
  { title = "実数 (Float)", path = "algebra.float.md" },
  { title = "複素数", path = "algebra.complex.md" },
  { title = "超数", path = "algebra.hyper.md" },
  { title = "行列", path = "algebra.matrix.md" },
]

[[pages]]
title = "剰余付き整数"
level = 2

[[pages]]
title = "ModInt"
path = "algebra.modint.md"

[[pages]]
title = "作用"
level = 2
items = [
  { title = "作用の定義", path = "algebra.act.md" },
  { title = "加算作用", path = "algebra.act.add.md" },
  { title = "代入作用", path = "algebra.act.assign.md" },
]

[[pages]]
title = "グラフ"

[[pages]]
title = "最短路"
level = 2
items = [
  { title = "ダイクストラ法", path = "graph.dij.md" },
  { title = "ワーシャル-フロイド法", path = "graph.wall.md" },
  { title = "ベルマンフォード法", path = "graph.bellmanford.md" },
]

[[pages]]
title = "無向グラフ"
level = 2
items = [
  { title = "二部グラフ判定", path = "graph.undirected.bipartite.md" },
  { title = "直径", path = "graph.undirected.diameter.md" },
]

[[pages]]
title = "最小全域木"
level = 2
items = [
  { title = "プリム法", path = "graph.prim.md" },
  { title = "クラスカル法", path = "graph.kruskal.md" },
]

[[pages]]
title = "木"
level = 2
items = [
  { title = "高さ", path = "graph.tree.height.md" },
  { title = "直径", path = "graph.tree.diameter.md" },
  { title = "最小共通祖先", path = "graph.tree.lca.md" },
]

[[pages]]
title = "有向グラフ"
level = 2
items = [
  { title = "最大流量", path = "graph.maxflow.md" },
  { title = "トポロジカルソート", path = "graph.topological.md" },
  { title = "強連結成分分解", path = "graph.scc.md" },
]

[[pages]]
title = "数列"

[[pages]]
title = "累積和"
level = 2
items = [
  { title = "一次元累積和", path = "seq.cumsum1d.md" },
  { title = "二次元累積和", path = "seq.cumsum2d.md" },
]

[[pages]]
title = "区間木"
level = 2

[[pages]]
title = "BIT"
level = 3
items = [
  { title = "BIT", path = "seq.bit.md" },
  { title = "区間加算を処理する BIT", path = "seq.bit_cumulative.md" },
]

[[pages]]
title = "セグメントツリー"
level = 3
items = [
  { title = "セグメントツリー", path = "seq.segment_tree.md" },
  { title = "RMQ", path = "seq.rmq.md" },
  { title = "加法セグメントツリー", path = "seq.segment_tree_sum.md" },
  { title = "乗法セグメントツリー", path = "seq.segment_tree_prod.md" },
]

[[pages]]
title = "遅延セグメントツリー"
level = 3
items = [
  { title = "遅延セグメントツリー", path = "seq.lazy_segment_tree.md" },
  { title = "区間代入 RMQ", path = "seq.ranged_assign_rmq.md" },
  { title = "区間加算 RMQ", path = "seq.ranged_add_rmq.md" },
  { title = "区間加算 加法セグメントツリー", path = "seq.ranged_add_segment_tree_sum.md" },
]

[[pages]]
title = "その他数列アルゴリズム"
level = 2

[[pages]]
title = "最長増加部分列"
path = "seq.lis.md"

[[pages]]
title = "中央値ヒープ"
path = "seq.median.md"

[[pages]]
title = "スライド最小値"
path = "seq.slide_min.md"

[[pages]]
title = "BitVecBool"
path = "seq.bitvecbool.md"

[[pages]]
title = "FFT 畳み込み"
path = "fft.convolution.md"

[[pages]]
title = "二次元ユークリッド幾何"

[[pages]]
title = "図形の定義"
level = 2
items = [
  { title = "点", path = "geo.2d.point.md" },
  { title = "直線, 線分", path = "geo.2d.line.md" },
  { title = "多角形", path = "geo.2d.polygon.md" },
  { title = "円", path = "geo.2d.circle.md" },
]

[[pages]]
title = "線分"
level = 2
items = [
  { title = "線分と点の接触判定", path = "geo.2d.ccw.md" },
  { title = "線分と線分の交差判定", path = "geo.2d.intersection.md" },
]

[[pages]]
title = "多角形"
level = 2
items = [
  { title = "三角形の外接円", path = "geo.2d.circum.md" },
  { title = "多角形の内外判定", path = "geo.2d.isin_poly.md" },
  { title = "凸包", path = "geo.2d.convex_hull.md" },
]

[[pages]]
title = "円"
level = 2
items = [
  { title = "円と円との接触関係", path = "geo.2d.circle.intersection.md" },
]

[[pages]]
title = "格子点上の幾何"
level = 2
items = [
  { title = "点", path = "geo.2d.int.point.md" },
  { title = "直線", path = "geo.2d.int.line.md" },
]

[[pages]]
title = "その他幾何アルゴリズム"
level = 2
items = [
  { title = "極座標", path = "geo.polar.md" },
  { title = "Convex-Hull Trick (CHT)", path = "geo.cht.md" },
  { title = "最近点対", path = "geo.closest_pair.md" },
]

[[pages]]
title = "集合"

[[pages]]
title = "UnionFind"
path = "set.union_find.md"

[[pages]]
title = "BitSet"
path = "set.bitset.md"

[[pages]]
title = "部分集合及びその部分集合の列挙"
path = "set.subbitset.md"

[[pages]]
title = "多重集合"
path = "collections.multiset.md"

[[pages]]
title = "アルゴリズム"

[[pages]]
title = "動的計画法"
level = 2
items = [
  { title = "01-ナップザック", path = "dp.knapsack.01.md" },
]

[[pages]]
title = "二分探索"
level = 2
items = [
  { title = "二分探索", path = "bin.search.md" },
]

[[pages]]
title = "循環検出"
level = 2
items = [
  { title = "フロイドの$\\rho$アルゴリズム", path = "algorithm.rho.md" },
]

[[pages]]
title = "連立一次方程式"
level = 2
items = [
  { title = "Gauss-Jordan の消去法", path = "algorithm.gauss_jordan.md" },
]

[[pages]]
title = "最適化"
items = [
  { title = "燃やす埋める問題", path = "opt.moyasu_umeru.md" },
  { title = "2-SAT", path = "opt.2sat.md" },
  { title = "乱択3-SAT", path = "opt.3sat.md" },
]

[[pages]]
title = "自然数・整数"

[[pages]]
title = "自然数・整数の関数・定理"
level = 2
items = [
  { title = "GCD", path = "num.gcd.md" },
  { title = "拡張GCD", path = "num.exgcd.md" },
  { title = "二項係数 (パスカルの三角形)", path = "num.binom.pascal.md" },
  { title = "二項係数 (ModInt)", path = "num.binom.modint.md" },
  { title = "離散対数", path = "num.dislog.md" },
  { title = "完全順列", path = "num.derangement.md" },
  { title = "オイラーの関数", path = "num.euler_phi.md" },
  { title = "メビウス関数", path = "num.moebius.md" },
  { title = "自然数の対 ↔ 自然数 の変換", path = "num.n_vs_nn.md" },
  { title = "最小自由数 (最小除外数)", path = "num.mex.md" },
  { title = "中国人剰余定理", path = "num.chinese.md" },
]

[[pages]]
title = "素数"
level = 2
items = [
  { title = "エラトステネスの篩", path = "prime.sieve.md" },
  { title = "ミラー・ラビン素数判定", path = "prime.MillerRabin.md" },
  { title = "フェルマーの小定理", path = "prime.fermat.little.md" },
  { title = "素因数分解", path = "prime.factorize.md" },
]

[[pages]]
title = "組み合わせのイテレーター"
level = 2
items = [
  { title = "階乗 - \\(n!\\)", path = "num.iter.perm.md" },
  { title = "冪乗 - $n^m$", path = "num.iter.powperm.md" },
  { title = "二項係数 - ${}_nC{}_m$", path = "num.iter.comb.md" },
]

[[pages]]
title = "乱数"
level = 2
items = [
  { title = "線形合同法", path = "rand.lcg.md" },
  { title = "Xor-Shift 法", path = "rand.xorshift.md" },
]

[[pages]]
title = "文字列 (Vector)"

[[pages]]
title = "文字列検索"
level = 2
items = [
  { title = "Shift-And", path = "string.shift-and.md" },
  { title = "Z-alogirhtm", path = "string.z.md" },
  { title = "接尾辞配列 (SA)", path = "string.suffix-array.md" },
  { title = "SA による文字列検索", path = "string.sa-search.md" },
]

[[pages]]
title = "回文"
level = 2
items = [
  { title = "manacher", path = "string.manacher.md" },
]

[[pages]]
title = "圧縮"
level = 2
items = [
  { title = "Run-length", path = "string.runlength.md" },
]

[[pages]]
title = "時間/時刻"

[[pages]]
title = "制限時間付きループ"
level = 2

[[pages]]
title = "loop_timeout_ms! マクロ"
path = "time.while.md"

[[pages]]
title = "暦"
level = 2
items = [
  { title = "ツェラーの公式", path = "cal.zeller.md" },
  { title = "閏年判定", path = "cal.uruu.md" },
]

[[pages]]
title = "ハッシュ"

[[pages]]
title = "Zobrist Hash"
path = "hash.zobrist.md"

[[pages]]
title = "Rolling Hash"
path = "hash.rolling.md"

[[pages]]
title = "文字列ハッシュ"
path = "hash.string.md"

[[pages]]
title = "collections"

[[pages]]
title = "defaultmap"
path = "collections.defaultdict.md"

[[pages]]
title = "リスト内包表記マクロ"
path = "collections.list_comprehension_macro.md"

[[pages]]
title = "misc"

[[pages]]
title = "近傍"
path = "misc.neighbor.md"

[[pages]]
title = "座標圧縮"
path = "misc.coodinate_compression.md"
